project_id                    = "tawa-ai"
location                      = "us-central1"
github_repo                   = "tawa-ai/kakhovka"
github_branch_pattern         = "refs/heads/main"
service_account_name          = "tawa-ai-kakhovka"
workload_identity_pool_id     = "tawa-ai-kakhovka-gha"
workload_identity_provider_id = "tawa-ai-kakhovka-gha"
