name: Terraform Plan on PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'

permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: "tawa-ai"
          workload_identity_provider:  "projects/60956311838/locations/global/workloadIdentityPools/tawa-ai-kakhovka-gha-branch/providers/tawa-ai-kakhovka-gha"
          service_account: 'tawa-ai-kakhovka-branch@tawa-ai.iam.gserviceaccount.com'
      
      - name: Terraform Init and Plan - Tawa Ai GCP
        id: plan-tawa
        run: |
          cd modules/service/gcp/tawa-ai
          terraform init -no-color
          terraform plan -no-color -out=tfplan
          terraform show -no-color tfplan > plan.txt
          echo "tawa_plan<<EOF" >> $GITHUB_ENV
          cat plan.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
       
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tawa_plan = process.env.tawa_plan;
            const comment = `## Terraform Plan Results 🔍
            
            <details>
            <summary>Tawa AI Plan</summary>
            
            \`\`\`terraform
            ${tawa_plan}
            \`\`\`
            </details>
            
            *Workflow: [${context.workflow}](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment 
            });
